### ISSUE TITLE
when mailaddress is provided a double "mailto" is added to the code

### ISSUE THREAD

**Issue by mzeinstra** [sparcopen/speakers-database#5]
It seems like {{Email To}} already contains a "mailto".

Steps to reproduce:

find an entry that has an email adress
click on the name
notice that the mail app prepends "mailto"

**Comment by char-siuu-bao** [comment]
Thanks for flagging this! Would it be best to remove the "mailto" from the {{Email To}} field? (that's easy for me to do!)

**Comment by JosephMcArthur** [comment]
Seems taking both out is okay (which it what I just did). This also fixed a bug I saw where it would open two email windows.

@lorrainechu3n will leave you to close if you're happy

**Comment by char-siuu-bao** [comment]
Thanks Joe!
